"""
Configuration Package for Ultimate Trading Bot v2.2.

This package provides centralized configuration management for the entire
trading bot including settings, logging, API configs, and more.
"""

from config.settings import (
    Settings,
    Environment,
    TradingMode,
    LogLevel,
    DatabaseType,
    DatabaseSettings,
    RedisSettings,
    AlpacaSettings,
    OpenAISettings,
    TradingSessionSettings,
    RiskManagementSettings,
    NotificationSettings,
    BacktestSettings,
    UISettings,
    MonitoringSettings,
    get_settings,
    reload_settings,
    settings,
)

from config.logging_config import (
    LoggingConfig,
    LogFormat,
    LogDestination,
    LoggingManager,
    TradeLogger,
    JSONFormatter,
    ColorizedFormatter,
    setup_logging,
    get_logger,
    get_trade_logger,
)

from config.constants import (
    VERSION,
    OrderSide,
    OrderType,
    OrderStatus,
    PositionSide,
    TimeInForce,
    AssetClass,
    MarketSession,
    SignalType,
    TrendDirection,
    VolatilityRegime,
    MarketCondition,
    StrategyMode,
    Timeframe,
    TIMEFRAME_MINUTES,
    INDICATOR_DEFAULTS,
    RISK_DEFAULTS,
    RATE_LIMITS,
    ML_DEFAULTS,
    SENTIMENT_THRESHOLDS,
    ErrorCode,
    HTTPStatus,
)

from config.api_config import (
    APIConfig,
    AlpacaAPIConfig,
    AlpacaEndpoints,
    YahooFinanceConfig,
    PolygonAPIConfig,
    IEXCloudConfig,
    NewsAPIConfig,
    WebSocketConfig,
    APIEnvironment,
    DataFeed,
    EndpointBuilder,
    get_api_config,
    reload_api_config,
    api_config,
)

from config.strategy_config import (
    StrategyConfig,
    StrategyType,
    SignalStrength,
    MarketRegime,
    BaseStrategyConfig,
    RSIStrategyConfig,
    MACDStrategyConfig,
    BollingerBandsStrategyConfig,
    MomentumStrategyConfig,
    MeanReversionStrategyConfig,
    TrendFollowingStrategyConfig,
    BreakoutStrategyConfig,
    VWAPStrategyConfig,
    IchimokuStrategyConfig,
    MLStrategyConfig,
    AISentimentStrategyConfig,
    AIConsensusStrategyConfig,
    CompositeStrategyConfig,
    get_strategy_config,
    reload_strategy_config,
    strategy_config,
)

from config.risk_config import (
    RiskConfig,
    RiskLevel,
    PositionSizingMethod,
    StopLossType,
    TakeProfitType,
    PositionSizingConfig,
    StopLossConfig,
    TakeProfitConfig,
    DrawdownConfig,
    PortfolioRiskConfig,
    VaRConfig,
    RiskLimitsConfig,
    get_risk_config,
    reload_risk_config,
    risk_config,
    RISK_PROFILES,
    create_risk_config_from_profile,
)

from config.openai_config import (
    OpenAIConfig,
    OpenAIModel,
    TaskType,
    ModelConfig,
    TaskModelMapping,
    RateLimitConfig,
    BudgetConfig,
    CacheConfig,
    SafetyConfig,
    MODEL_PRICING,
    get_openai_config,
    reload_openai_config,
    openai_config,
    SYSTEM_PROMPTS,
)

from config.prompts_config import (
    PromptTemplate,
    PromptCategory,
    PromptRegistry,
    prompt_registry,
    get_prompt,
    format_prompt,
    SENTIMENT_SYSTEM_PROMPT,
    CHART_SYSTEM_PROMPT,
    TRADING_SYSTEM_PROMPT,
    RISK_SYSTEM_PROMPT,
    MARKET_SYSTEM_PROMPT,
    STRATEGY_SYSTEM_PROMPT,
    NEWS_SYSTEM_PROMPT,
)


__all__ = [
    # Settings
    "Settings",
    "Environment",
    "TradingMode",
    "LogLevel",
    "DatabaseType",
    "DatabaseSettings",
    "RedisSettings",
    "AlpacaSettings",
    "OpenAISettings",
    "TradingSessionSettings",
    "RiskManagementSettings",
    "NotificationSettings",
    "BacktestSettings",
    "UISettings",
    "MonitoringSettings",
    "get_settings",
    "reload_settings",
    "settings",
    # Logging
    "LoggingConfig",
    "LogFormat",
    "LogDestination",
    "LoggingManager",
    "TradeLogger",
    "JSONFormatter",
    "ColorizedFormatter",
    "setup_logging",
    "get_logger",
    "get_trade_logger",
    # Constants
    "VERSION",
    "OrderSide",
    "OrderType",
    "OrderStatus",
    "PositionSide",
    "TimeInForce",
    "AssetClass",
    "MarketSession",
    "SignalType",
    "TrendDirection",
    "VolatilityRegime",
    "MarketCondition",
    "StrategyMode",
    "Timeframe",
    "TIMEFRAME_MINUTES",
    "INDICATOR_DEFAULTS",
    "RISK_DEFAULTS",
    "RATE_LIMITS",
    "ML_DEFAULTS",
    "SENTIMENT_THRESHOLDS",
    "ErrorCode",
    "HTTPStatus",
    # API Config
    "APIConfig",
    "AlpacaAPIConfig",
    "AlpacaEndpoints",
    "YahooFinanceConfig",
    "PolygonAPIConfig",
    "IEXCloudConfig",
    "NewsAPIConfig",
    "WebSocketConfig",
    "APIEnvironment",
    "DataFeed",
    "EndpointBuilder",
    "get_api_config",
    "reload_api_config",
    "api_config",
    # Strategy Config
    "StrategyConfig",
    "StrategyType",
    "SignalStrength",
    "MarketRegime",
    "BaseStrategyConfig",
    "RSIStrategyConfig",
    "MACDStrategyConfig",
    "BollingerBandsStrategyConfig",
    "MomentumStrategyConfig",
    "MeanReversionStrategyConfig",
    "TrendFollowingStrategyConfig",
    "BreakoutStrategyConfig",
    "VWAPStrategyConfig",
    "IchimokuStrategyConfig",
    "MLStrategyConfig",
    "AISentimentStrategyConfig",
    "AIConsensusStrategyConfig",
    "CompositeStrategyConfig",
    "get_strategy_config",
    "reload_strategy_config",
    "strategy_config",
    # Risk Config
    "RiskConfig",
    "RiskLevel",
    "PositionSizingMethod",
    "StopLossType",
    "TakeProfitType",
    "PositionSizingConfig",
    "StopLossConfig",
    "TakeProfitConfig",
    "DrawdownConfig",
    "PortfolioRiskConfig",
    "VaRConfig",
    "RiskLimitsConfig",
    "get_risk_config",
    "reload_risk_config",
    "risk_config",
    "RISK_PROFILES",
    "create_risk_config_from_profile",
    # OpenAI Config
    "OpenAIConfig",
    "OpenAIModel",
    "TaskType",
    "ModelConfig",
    "TaskModelMapping",
    "RateLimitConfig",
    "BudgetConfig",
    "CacheConfig",
    "SafetyConfig",
    "MODEL_PRICING",
    "get_openai_config",
    "reload_openai_config",
    "openai_config",
    "SYSTEM_PROMPTS",
    # Prompts Config
    "PromptTemplate",
    "PromptCategory",
    "PromptRegistry",
    "prompt_registry",
    "get_prompt",
    "format_prompt",
    "SENTIMENT_SYSTEM_PROMPT",
    "CHART_SYSTEM_PROMPT",
    "TRADING_SYSTEM_PROMPT",
    "RISK_SYSTEM_PROMPT",
    "MARKET_SYSTEM_PROMPT",
    "STRATEGY_SYSTEM_PROMPT",
    "NEWS_SYSTEM_PROMPT",
]
